### ISSUE TITLE
pv¬p doesn't work

### ISSUE THREAD

**Issue by falvear210** [wo/tpg#7]
The formula pv¬p does not work. The error says: "I don't understand '¬' in 'pv¬p'. Missing operator?" Tried with (p)v(¬p), 
pv(¬p), and (pv(¬p)) with no success.

**Comment by falvear210** [comment]
> The formula pv¬p does not work. The error says: "I don't understand '¬' in 'pv¬p'. Missing operator?" Tried with (p)v(¬p),
> pv(¬p), and (pv(¬p)) with no success.

Strangely, the formulas previously mentioned work in iOS Chrome but not in macOS Chrome or Safari

**Comment by wo** [comment]
Thanks. The problem is that the letter 'v' is often used as a variable, e.g. in 'Fvw'. Compare 'p -> (qvr)' and 'Fa -> (Gavr)'. In the first sentence, 'v' is probably meant as disjunction, in the second it might be meant as disjunction but it might equally be meant as a singular term. I've settled on reading 'v' as disjunction only if there's a space on either side. This is now mentioned in the error message.

**Comment by falvear210** [comment]
Thank you! This is an awesome tool btw, very well executed!
